export const normalizeWord = (word: string): string => {
  const normalized = word.normalize('NFKC');
  return normalized.replace(/[\u2000-\u206F\u2E00-\u2E7F\\'!"#$%&()*+,\-.\/:;<=>?@\[\]^_`{|}~]/g, '').toLowerCase();
};

export const cleanText = (text: string): string => {
  return text.replace(/\binaudible\b[.,;:!?"\'\-]*/gi, '');
};

export const contractionMap = (): { [key: string]: string } => {
  return {
    'they are': 'theyre',
    'we are': 'were',
    'you are': 'youre',
    'i am': 'im',
    'do not': 'dont',
    'does not': 'doesnt',
    'did not': 'didnt',
    'is not': 'isnt',
    'are not': 'arent',
    'was not': 'wasnt',
    'were not': 'werent',
    'have not': 'havent',
    'has not': 'hasnt',
    'had not': 'hadnt',
    'will not': 'wont',
    'would not': 'wouldnt',
    'should not': 'shouldnt',
    'could not': 'couldnt',
    'cannot': 'cant',
    'can not': 'cant',
    'it is': 'its',
    'it will': 'itll',
    'that is': 'thats',
    'there is': 'theres',
    'what is': 'whats',
    'who is': 'whos',
    'let us': 'lets',
    'i will': 'ill',
    'you will': 'youll',
    'he will': 'hell',
    'she will': 'shell',
    'we will': 'well',
    'they will': 'theyll',
    'i have': 'ive',
    'you have': 'youve',
    'we have': 'weve',
    'they have': 'theyve',
    'should have': 'shouldve',
    'would have': 'wouldve',
    'could have': 'couldve',
    'might have': 'mightve',
    'must have': 'mustve',
    'i would': 'id',
    'you would': 'youd',
    'he would': 'hed',
    'she would': 'shed',
    'we would': 'wed',
    'they would': 'theyd',
    'i had': 'id',
    'you had': 'youd',
    'he had': 'hed',
    'she had': 'shed',
    'we had': 'wed',
    'they had': 'theyd',
    "aren't": "arent",
    "can't": "cant",
    "couldn't": "couldnt",
    "didn't": "didnt",
    "doesn't": "doesnt",
    "don't": "dont",
    "hadn't": "hadnt",
    "hasn't": "hasnt",
    "haven't": "havent",
    "he'd": "hed",
    "he'll": "hell",
    "he's": "hes",
    "i'd": "id",
    "i'll": "ill",
    "i'm": "im",
    "i've": "ive",
    "isn't": "isnt",
    "it'd": "itd",
    "it'll": "itll",
    "it's": "its",
    "let's": "lets",
    "mightn't": "mightnt",
    "mustn't": "mustnt",
    "shan't": "shant",
    "she'd": "shed",
    "she'll": "shell",
    "she's": "shes",
    "shouldn't": "shouldnt",
    "that's": "thats",
    "there's": "theres",
    "they'd": "theyd",
    "they'll": "theyll",
    "they're": "theyre",
    "they've": "theyve",
    "we'd": "wed",
    "we're": "were",
    "we've": "weve",
    "weren't": "werent",
    "what'll": "whatll",
    "what're": "whatre",
    "what's": "whats",
    "what've": "whatve",
    "where's": "wheres",
    "who'd": "whod",
    "who'll": "wholl",
    "who're": "whore",
    "who's": "whos",
    "who've": "whove",
    "won't": "wont",
    "wouldn't": "wouldnt",
    "you'd": "youd",
    "you'll": "youll",
    "you're": "youre",
    "you've": "youve",
  };
};

export const mapExpandedToContraction = (text: string): string => {
  const mapping = contractionMap();
  
  const normalizeForMap = (s: string): string => {
    const normalized = s.normalize('NFKC');
    return normalized.replace(/[\u2000-\u206F\u2E00-\u2E7F\\'!"#$%&()*+,\-.\/:;<=>?@\[\]^_`{|}~]/g, '').toLowerCase();
  };
  
  let textNorm = normalizeForMap(text);
  
  Object.entries(mapping).forEach(([expanded, contraction]) => {
    const expandedNorm = normalizeForMap(expanded);
    textNorm = textNorm.replace(new RegExp(expandedNorm, 'g'), contraction);
  });
  
  return textNorm;
};

export const splitCompoundWords = (text: string): string => {
  const compounds: { [key: string]: string } = {
    'coldblooded': 'cold blooded',
    'warmblooded': 'warm blooded',
    'toadstool': 'toad stool',
    'bullfrog': 'bull frog',
    'tadpole': 'tad pole',
    'treefrog': 'tree frog',
    'springpeeper': 'spring peeper',
    'woodfrog': 'wood frog',
    'spadefoot': 'spade foot',
    'newtlike': 'newt like',
    'frogspawn': 'frog spawn',
    'pondweed': 'pond weed',
    'nighttime': 'night time',
    'seethrough': 'see through',
    'waterhole': 'water hole',
    'rainforest': 'rain forest',
    'sunbaked': 'sun baked',
    'backbone': 'back bone',
    'eggsac': 'egg sac',
    'overwinter': 'over winter',
    'underwater': 'under water',
    'daylight': 'day light',
    'earthworm': 'earth worm',
    'insectlike': 'insect like',
    'mouthpart': 'mouth part',
    'tailfin': 'tail fin',
    'webbedfeet': 'webbed feet',
    'webbedfoot': 'webbed foot',
    'notebook': 'note book',
    'blackboard': 'black board',
    'classroom': 'class room',
    'sunflower': 'sun flower',
    'football': 'foot ball',
    'basketball': 'basket ball',
    'baseball': 'base ball',
    'playground': 'play ground',
    'schoolyard': 'school yard',
    'lunchbox': 'lunch box',
    'toothbrush': 'tooth brush',
    'hairbrush': 'hair brush',
    'bedroom': 'bed room',
    'bathroom': 'bath room',
    'livingroom': 'living room',
    'diningroom': 'dining room',
    'bookshelf': 'book shelf',
    'bookshelves': 'book shelves',
    'snowman': 'snow man',
    'raincoat': 'rain coat',
    'fireman': 'fire man',
    'policeman': 'police man',
    'mailbox': 'mail box',
    'sandbox': 'sand box',
    'doghouse': 'dog house',
    'catfish': 'cat fish',
    'goldfish': 'gold fish',
    'starfish': 'star fish',
    'cupcake': 'cup cake',
    'birthdaycake': 'birthday cake',
    'pancake': 'pan cake',
    'cheesecake': 'cheese cake',
    'popcorn': 'pop corn',
    'peanutbutter': 'peanut butter',
    'strawberry': 'straw berry',
    'blueberry': 'blue berry',
    'raspberry': 'rasp berry',
    'blackberry': 'black berry',
    'greenhouse': 'green house',
    'lighthouse': 'light house',
    'wheelchair': 'wheel chair',
    'newspaper': 'news paper',
    'airport': 'air port',
    'rainbow': 'rain bow',
    'moonlight': 'moon light',
    'sunlight': 'sun light',
    'starlight': 'star light',
    'daydream': 'day dream',
    'nightmare': 'night mare',
    'overcoat': 'over coat',
    'underdog': 'under dog',
    'overhead': 'over head',
    'underfoot': 'under foot',
    'upstairs': 'up stairs',
    'downstairs': 'down stairs',
    'outdoors': 'out doors',
    'indoors': 'in doors',
    'outfield': 'out field',
    'infield': 'in field',
    'outlaw': 'out law',
    'inlet': 'in let',
    'outlet': 'out let',
    'upset': 'up set',
    'downpour': 'down pour',
    'outcome': 'out come',
    'income': 'in come',
    'outbreak': 'out break',
    'input': 'in put',
    'output': 'out put',
    'outlook': 'out look',
    'insight': 'in sight',
    'oversight': 'over sight',
    'oversee': 'over see',
    'overdo': 'over do',
    'undo': 'un do',
    'redo': 're do',
    'preview': 'pre view',
    'review': 're view',
    'replay': 're play',
    'rebuild': 're build',
    'recycle': 're cycle',
    'recharge': 're charge',
    'rearrange': 're arrange',
    'reappear': 're appear',
    'reapply': 're apply',
    'reconnect': 're connect',
    'reconsider': 're consider',
    'reconstruct': 're construct',
    'recount': 're count',
    'recover': 're cover',
    'recreate': 're create',
    'redefine': 're define',
    'rediscover': 're discover',
    'reenter': 're enter',
    'refill': 're fill',
    'refocus': 're focus',
    'refresh': 're fresh',
    'regain': 're gain',
    'regrow': 're grow',
    'rehash': 're hash',
    'reheat': 're heat',
    'rejoin': 're join',
    'relive': 're live',
    'remake': 're make',
    'rematch': 're match',
    'remove': 're move',
    'rename': 're name',
    'renew': 're new',
    'reopen': 're open',
    'replace': 're place',
    'report': 're port',
    'resend': 're send',
    'reset': 're set',
    'resign': 're sign',
    'resist': 're sist',
    'resolve': 're solve',
    'resort': 're sort',
    'resource': 're source',
    'respect': 're spect',
    'respond': 're spond',
    'restart': 're start',
    'restore': 're store',
    'restrict': 're strict',
    'result': 're sult',
    'resume': 're sume',
    'retake': 're take',
    'retell': 're tell',
    'retire': 're tire',
    'return': 're turn',
    'reuse': 're use',
    'reveal': 're veal',
    'revenge': 're venge',
    'reverse': 're verse',
    'revise': 're vise',
    'revisit': 're visit',
    'revoke': 're voke',
    'reward': 're ward',
    'rewind': 're wind',
    'rewrite': 're write',
  };

  Object.entries(compounds).forEach(([compound, split]) => {
    text = text.replace(new RegExp(`\\b${compound}\\b`, 'gi'), split);
  });
  
  return text;
};
